name: Firebase Deploy

on:
  push:
    branches:
      - main  # Ana branch'iniz neyse onun ismini yazın (örneğin 'master' ya da 'main')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Deploy to Firebase
      run: npm run build && firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


